# Generated by Django 4.2.7 on 2026-02-02 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('pl', 'Polski')], max_length=10, verbose_name='Мова тесту')),
                ('level', models.CharField(choices=[('beginner', 'Початковий'), ('elementary', 'Елементарний'), ('intermediate', 'Середній'), ('upper_intermediate', 'Вище середнього'), ('advanced', 'Просунутий')], max_length=20, verbose_name='Рівень')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='Відповідь користувача')),
                ('audio_answer_url', models.URLField(blank=True, null=True, verbose_name='URL аудіо відповіді')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Правильно')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Отримано балів')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='Відгук AI')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Відповідано о')),
            ],
            options={
                'verbose_name': 'Відповідь на питання тесту',
                'verbose_name_plural': 'Відповіді на питання тестів',
                'db_table': 'test_answers',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Опис')),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тривалість (хвилин)')),
                ('total_score', models.IntegerField(default=100, verbose_name='Максимальний бал')),
            ],
            options={
                'verbose_name': 'Тип тесту',
                'verbose_name_plural': 'Типи тестів',
                'db_table': 'test_types',
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening', 'Аудіювання'), ('reading', 'Читання'), ('writing', 'Письмо'), ('speaking', 'Говоріння')], max_length=20, verbose_name='Тип секції')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тривалість (хвилин)')),
                ('max_score', models.IntegerField(default=25, verbose_name='Максимальний бал')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Секція тесту',
                'verbose_name_plural': 'Секції тестів',
                'db_table': 'test_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Вибір відповіді'), ('fill_blank', 'Заповнити пропуск'), ('true_false', 'Правда/Неправда'), ('matching', 'Зіставлення'), ('short_answer', 'Коротка відповідь'), ('essay', 'Есе'), ('listening_audio', 'Аудіювання з аудіо'), ('speaking_record', 'Говоріння з записом')], max_length=20, verbose_name='Тип питання')),
                ('question_text', models.TextField(verbose_name='Текст питання')),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='URL аудіо')),
                ('audio_text', models.TextField(blank=True, null=True, verbose_name='Текст для аудіо (генерація через AI)')),
                ('correct_answer', models.TextField(verbose_name='Правильна відповідь')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Варіанти відповідей')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Бали')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Згенеровано AI')),
                ('ai_prompt', models.TextField(blank=True, null=True, verbose_name='Промпт для AI')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testsection', verbose_name='Секція')),
            ],
            options={
                'verbose_name': 'Питання тесту',
                'verbose_name_plural': 'Питання тестів',
                'db_table': 'test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процесі'), ('completed', 'Завершено'), ('abandoned', 'Перервано')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Почато о')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено о')),
                ('total_score', models.IntegerField(default=0, verbose_name='Загальний бал')),
                ('max_score', models.IntegerField(default=100, verbose_name='Максимальний бал')),
                ('listening_score', models.IntegerField(default=0, verbose_name='Бал за аудіювання')),
                ('reading_score', models.IntegerField(default=0, verbose_name='Бал за читання')),
                ('writing_score', models.IntegerField(default=0, verbose_name='Бал за письмо')),
                ('speaking_score', models.IntegerField(default=0, verbose_name='Бал за говоріння')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Спроба тесту',
                'verbose_name_plural': 'Спроби тестів',
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
