# Generated by Django 4.2.28 on 2026-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_test_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('pl', 'Polski')], max_length=10, verbose_name='Мова тесту'),
        ),
    ]
