# Generated by Django 4.2.28 on 2026-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswer',
            name='audio_answer_url',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='listening_score',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='speaking_score',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='audio_text',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='audio_url',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Вибір відповіді'), ('fill_blank', 'Заповнити пропуск'), ('true_false', 'Правда/Неправда'), ('matching', 'Зіставлення'), ('short_answer', 'Коротка відповідь'), ('essay', 'Есе')], max_length=20, verbose_name='Тип питання'),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='section_type',
            field=models.CharField(choices=[('reading', 'Читання'), ('writing', 'Письмо')], max_length=20, verbose_name='Тип секції'),
        ),
    ]
