# Generated by Django 4.2.28 on 2026-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_testanswer_audio_answer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Промпт'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Згенеровано'),
        ),
    ]
