# Generated by Django 6.0.2 on 2026-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_image_alter_testanswer_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Вибір правильної відповіді'), ('fill_blank', 'Заповни пропуски'), ('true_false', 'Логічний вибір'), ('matching', 'Виклик зіставлення'), ('short_answer', 'Експрес-відповідь'), ('essay', 'Творче есе')], max_length=20, verbose_name='Тип питання'),
        ),
    ]
