# Generated by Django 4.2.7 on 2026-02-02 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('pl', 'Polski')], max_length=10, verbose_name='Мова курсу')),
                ('level', models.CharField(choices=[('beginner', 'Початковий'), ('elementary', 'Елементарний'), ('intermediate', 'Середній'), ('upper_intermediate', 'Вище середнього'), ('advanced', 'Просунутий')], max_length=20, verbose_name='Рівень')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Вибір відповіді'), ('fill_blank', 'Заповнити пропуск'), ('translation', 'Переклад'), ('listening', 'Аудіювання'), ('speaking', 'Говоріння'), ('ai_generated', 'AI Генерована')], max_length=20, verbose_name='Тип вправи')),
                ('question', models.TextField(verbose_name='Питання')),
                ('correct_answer', models.TextField(verbose_name='Правильна відповідь')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Варіанти відповідей')),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Бали')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Згенеровано AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вправа',
                'verbose_name_plural': 'Вправи',
                'db_table': 'exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('content', models.TextField(verbose_name='Контент уроку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='Відповідь користувача')),
                ('is_correct', models.BooleanField(verbose_name='Правильно')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='Відгук AI')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Отримано балів')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Спробовано о')),
            ],
            options={
                'verbose_name': 'Спроба вправи',
                'verbose_name_plural': 'Спроби вправ',
                'db_table': 'user_exercise_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено о')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Почато о')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Прогрес по уроку',
                'verbose_name_plural': 'Прогрес по уроках',
                'db_table': 'user_lesson_progress',
            },
        ),
    ]
