# Generated by Django 4.2.28 on 2026-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_exercise_lesson_coursetest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('uk', 'Ukrainian')], max_length=10, verbose_name='Мова курсу'),
        ),
    ]
