# Generated by Django 6.0.2 on 2026-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Вибір правильної відповіді'), ('fill_blank', 'Заповни пропуски'), ('translation', 'Майстер перекладу'), ('listening', 'Аудіо-аналіз'), ('speaking', 'Мовна практика'), ('ai_generated', 'Майстер-квест')], max_length=20, verbose_name='Тип вправи'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Згенеровано'),
        ),
        migrations.AlterField(
            model_name='userexerciseattempt',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Відгук'),
        ),
    ]
