upstream movly_app {
    server web:8000;
}

server {
    listen 80;

    # Обробка статичних файлів через Nginx (це швидше)
    location /static/ {
        alias /app/staticfiles/;
    }

    # Все інше проксіюємо на Django (Gunicorn)
    location / {
        proxy_pass http://movly_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
