# Generated by Django 4.2.7 on 2026-02-02 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('exercise_generation', 'Генерація вправи'), ('feedback', 'Відгук'), ('answer_check', 'Перевірка відповіді'), ('audio_generation', 'Генерація аудіо')], max_length=50, verbose_name='Тип взаємодії')),
                ('prompt', models.TextField(verbose_name='Запит')),
                ('response', models.TextField(verbose_name='Відповідь AI')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Використано токенів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Взаємодія з AI',
                'verbose_name_plural': 'Взаємодії з AI',
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('exercises_completed', models.IntegerField(default=0, verbose_name='Виконано вправ')),
                ('lessons_completed', models.IntegerField(default=0, verbose_name='Завершено уроків')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='Час навчання (хв)')),
                ('accuracy_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Точність (%)')),
                ('ai_interactions_count', models.IntegerField(default=0, verbose_name='Взаємодій з AI')),
            ],
            options={
                'verbose_name': 'Аналітика навчання',
                'verbose_name_plural': 'Аналітика навчання',
                'db_table': 'learning_analytics',
                'ordering': ['-date'],
            },
        ),
    ]
