# Generated by Django 4.2.28 on 2026-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('exercise_generation', 'Генерація вправи'), ('feedback', 'Відгук'), ('answer_check', 'Перевірка відповіді')], max_length=50, verbose_name='Тип взаємодії'),
        ),
    ]
