# Generated by Django 6.0.2 on 2026-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_alter_aiinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinteraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Взаємодія', 'verbose_name_plural': 'Взаємодії'},
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='response',
            field=models.TextField(verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='learninganalytics',
            name='ai_interactions_count',
            field=models.IntegerField(default=0, verbose_name='Взаємодій'),
        ),
    ]
