# Generated by Django 4.2.7 on 2026-02-02 15:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('native_language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('ru', 'Русский')], default='uk', max_length=10, verbose_name='Рідна мова')),
                ('learning_language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('ru', 'Русский'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('pl', 'Polski')], default='en', max_length=10, verbose_name='Мова вивчення')),
                ('level', models.CharField(choices=[('beginner', 'Початковий'), ('elementary', 'Елементарний'), ('intermediate', 'Середній'), ('upper_intermediate', 'Вище середнього'), ('advanced', 'Просунутий')], default='beginner', max_length=20, verbose_name='Рівень')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons_completed', models.IntegerField(default=0, verbose_name='Пройдено уроків')),
                ('total_exercises_completed', models.IntegerField(default=0, verbose_name='Виконано вправ')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Поточна серія днів')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Найдовша серія днів')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Загальний досвід')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Остання активність')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Прогрес користувача',
                'verbose_name_plural': 'Прогрес користувачів',
                'db_table': 'user_progress',
            },
        ),
    ]
