# Generated by Django 4.2.28 on 2026-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='learning_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano')], default='en', max_length=10, verbose_name='Мова вивчення'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='native_language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=10, verbose_name='Рідна мова'),
        ),
    ]
