# Generated by Django 4.2.28 on 2026-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_learning_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='daily_goal',
            field=models.IntegerField(default=50, verbose_name='Щоденна ціль XP'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='daily_xp',
            field=models.IntegerField(default=0, verbose_name='Досвід за сьогодні'),
        ),
    ]
