# Generated by Django 4.2.28 on 2026-02-12 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprogress_daily_goal_userprogress_daily_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('icon', models.CharField(max_length=50, verbose_name='Іконка (FontAwesome class)')),
                ('criteria_type', models.CharField(choices=[('course_completed', 'Завершення курсу'), ('xp_reached', 'Досягнення XP'), ('streak_reached', 'Серія днів'), ('exercise_count', 'Кількість вправ')], max_length=50, verbose_name='Тип критерію')),
                ('criteria_value', models.IntegerField(verbose_name='Значення критерію')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Значок користувача',
                'verbose_name_plural': 'Значки користувачів',
                'db_table': 'user_badges',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
