# Generated by Django 6.0.2 on 2026-04-20 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('course_completed', 'Завершення курсу'), ('test_completed', 'Складання тесту'), ('xp_reached', 'Досягнення XP'), ('streak_reached', 'Серія днів'), ('exercise_count', 'Кількість вправ')], max_length=50, verbose_name='Тип критерію'),
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Слово/Фраза')),
                ('translation', models.CharField(max_length=255, verbose_name='Переклад')),
                ('language', models.CharField(max_length=10, verbose_name='Мова')),
                ('mastery_level', models.IntegerField(default=1, verbose_name='Рівень засвоєння')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='Останнє повторення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Слово користувача',
                'verbose_name_plural': 'Словник користувача',
                'db_table': 'user_vocabulary',
                'unique_together': {('user', 'word', 'language')},
            },
        ),
    ]
