# Generated by Django 6.0.2 on 2026-04-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_exercise_exercise_type_and_more'),
        ('users', '0005_alter_badge_criteria_type_userword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_words', to='courses.course', verbose_name='Курс/Тема'),
        ),
    ]
